module.exports = {
    appName: "your app name here", /*any string as name of your app*/
    appKey: "your appKey here", /* generated by trello */
    appSecret: "your appSecret here" /*also generated by trello * /
    callbackUrl: "" /*a valid http end point in your app that trello can callback*/
};